name: CI Pipeline

on:
  push:
    branches: ["*"] # Run on all branches
  pull_request:
    branches: [main] # Run when merging into main
  workflow_dispatch: # Optional: allows manual run from Actions tab

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Verify .env file (optional)
        run: |
          if [ ! -f .env ]; then
            echo "RADIUS_SHARED_SECRET=testsecret123" > .env
            echo "REDIS_HOST=localhost:6379" >> .env
            echo "RECORD_TTL_HOURS=24" >> .env
            echo "LOG_LEVEL=info" >> .env
            echo "LOG_FILE=/tmp/test.log" >> .env
          fi

      - name: Run Unit Tests
        run: make test-unit

      - name: Generate Coverage Report
        run: make coverage-report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out


  integration:
    name: Integration Tests + Build
    runs-on: ubuntu-latest
    needs: unit  # Waits until unit tests pass

    services:
      redis:
        image: redis:7.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Integration Tests
        run: make test-integration

      - name: Build binaries
        run: make build

      - name: Display Version Info
        run: make version
